name-template: '${{ tag_name }}'
tag-template: '${{ tag_name }}'
version-template: '${{ tag_name }}'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
      - 'readme'
change-template: '- ${{ message }} [#${{ pr_number }}](${{ url }}) by @${{ contributor }}'
no-changes-template: 'no changes'

prerelease: false
include-pre-releases: false
no-contributors-template: 'No contributors'

template: |
  ## What’s Changed
  $CHANGES

  ## Contributors
  {% if CONTRIBUTORS %}
  ## Contributors
  $CONTRIBUTORS
  {% endif %}